title: "Stefan Hoffelner"
email: "stefan.hoffelner@tuwien.ac.at"
description: "Academic webpage of Stefan Hoffelner, set theory and mathematical logic."
baseurl: ""
url: "https://stefanhoffelner.github.io"
lang: "en"

markdown: kramdown

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - _papers
